version: '3.9'

services:
  relay:
    environment:
      LOG_LEVEL: ${LOG_LEVEL:-INFO}
      RELAY_MODE: ${RELAY_MODE:-legacy}
    deploy:
      replicas: ${REPLICAS:-1}
  waku:
    deploy:
      replicas: 0
