version: '3.9'

services:   
  health:
    image: walletconnect/health-server:${TAG:-dev}
    build:
      context: ../../servers/health/
      dockerfile: Dockerfile
  relay:
    image: walletconnect/relay-server:${TAG:-dev}
    build:
      context: ../../servers/relay/
      dockerfile: Dockerfile    
