version: '3.9'

services:
  monorepo-tests:
    networks:
      - walletconnect-monorepo
    environment:
      - TEST_RELAY_URL=ws://relay:5000
    depends_on:
      relay:
        condition: service_healthy