name: build
on:
  push:
    branches:
      - v2.0
    tags:
      - "v*"

env:
  TERM: linux        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set env
        run: |
          echo "TAG=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
      - name: build docker images
        run: |
          ## pull latest image to improve build time
          TAG=latest make pull
          make build
          make build-dev
      - name: publish docker images
        run: |
          make publish
          make publish-dev
      - name: create latest tag
        run: |
          export TAG=latest
          make build-dev
          make publish-dev
        if: startsWith(github.ref, 'refs/tags/v')  
